version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: mytodoapp_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:4000 # backendのURL
    networks:
      - mytodo_network

  backend:
    build: ./backend
    container_name: mytodoapp_backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mytodo
      - DB_PORT=5432
    networks:
      - mytodo_network

  db:
    image: postgres:15
    container_name: mytodoapp_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mytodo
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mytodo_network

volumes:
  db_data:

networks:
  mytodo_network:
    driver: bridge
